# Generated by Django 3.2 on 2022-10-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='new project', max_length=30, null=True)),
                ('scripts', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('plan', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
