# Generated by Django 3.2 on 2022-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_projects',
            name='scripts',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
    ]
