# Generated by Django 3.2 on 2022-10-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_db_projects_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('des', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('project_id', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, default='队列中', max_length=10, null=True)),
            ],
        ),
    ]
