# Generated by Django 3.2 on 2022-10-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_db_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_django_task_mq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('message', models.TextField(default='{}')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
