# Generated by Django 3.2 on 2022-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_db_django_task_mq'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_tasks',
            name='mq_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='db_tasks',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
