# Generated by Django 3.2 on 2022-11-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20221026_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_projects',
            name='scripts',
        ),
        migrations.AlterField(
            model_name='db_projects',
            name='plan',
            field=models.CharField(blank=True, default='[]', max_length=1000, null=True),
        ),
    ]
